version: '3.9'

services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  backend:
    volumes:
      - ./backend:/app
    command: cargo watch -x run
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/whataclip

  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
